import PropTypes from 'prop-types';
import { DashboardIcon } from '../../components/DashboardIcons';
import { formatCurrency, formatDateTime, getPaymentLabel, getStatusLabel } from '../salesFormatters';

const SaleDetail = ({ sale, loading, onClose }) => {
  if (!sale && !loading) return null;
  return <aside className="sale-detail" aria-label="Detalle de venta"><div className="sale-detail-header"><div><span className="dashboard-eyebrow">Detalle de operación</span><h2>{sale ? `Venta #${String(sale._id || sale.id).slice(-8)}` : 'Cargando venta'}</h2></div><button type="button" className="sales-icon-button" onClick={onClose} aria-label="Cerrar detalle"><DashboardIcon name="X" size={18} /></button></div>{loading ? <div className="sales-detail-loading"><span className="sales-spinner" /> Consultando venta...</div> : <><div className="sale-detail-status"><span className={`sales-status sales-status-${String(sale.status || '').toLowerCase()}`}>{getStatusLabel(sale.status)}</span><span>{formatDateTime(sale.soldAt)}</span></div><dl className="sale-detail-meta"><div><dt>Empleado</dt><dd>{sale.employee?.nombre || sale.employee || 'No asignado'}</dd></div><div><dt>Turno</dt><dd>{sale.shift || 'No asignado'}</dd></div><div><dt>Pago</dt><dd>{getPaymentLabel(sale.payment?.method)}</dd></div></dl><div className="sale-detail-items"><span className="dashboard-eyebrow">Ítems</span>{(sale.items || []).map((item, index) => <div className="sale-detail-item" key={`${item.itemType}-${index}`}><div><strong>{item.itemType === 'FUEL' ? item.fuelType || 'Combustible' : 'Producto'}</strong><small>{item.quantity} × {formatCurrency(item.unitPrice)}</small></div><strong>{formatCurrency(item.total)}</strong></div>)}</div><div className="sale-detail-totals"><div><span>Subtotal</span><strong>{formatCurrency(sale.subtotal)}</strong></div><div><span>Impuestos</span><strong>{formatCurrency(sale.taxes)}</strong></div><div className="sale-detail-total"><span>Total</span><strong>{formatCurrency(sale.total)}</strong></div></div></>}</aside>;
};

SaleDetail.propTypes = { sale: PropTypes.shape({ _id: PropTypes.string, id: PropTypes.string, status: PropTypes.string, soldAt: PropTypes.string, employee: PropTypes.oneOfType([PropTypes.string, PropTypes.object]), shift: PropTypes.oneOfType([PropTypes.string, PropTypes.object]), payment: PropTypes.shape({ method: PropTypes.string }), items: PropTypes.arrayOf(PropTypes.object), subtotal: PropTypes.number, taxes: PropTypes.number, total: PropTypes.number }), loading: PropTypes.bool.isRequired, onClose: PropTypes.func.isRequired };
SaleDetail.defaultProps = { sale: null };
export default SaleDetail;